<%@ Page Title="" Language="C#" MasterPageFile="~/SgaGestionAcceso.Master" AutoEventWireup="true" CodeBehind="frmMenuConsulta.aspx.cs" Inherits="SgaGestionAcceso.WEB.Menu.frmMenuConsulta" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<div>
    <div class="panel">
            <h1 class="rounded">Búsqueda de
             Menu</h1>
            <br/>
              <table border="0" cellpadding="0" cellspacing="0" class="fix rounded Size700" 
                width="700">
                <tbody>
                    <tr>
                        <td>Objeto</td>
                        <td>
                               <asp:TextBox ID="txtCodigoObjeto" runat="server" CssClass="edit rounded" 
                                Width="300px" MaxLength="50"></asp:TextBox>                            
                        </td>
                    </tr>
                                  
                    <tr>
                        <td colspan="4">
                            <asp:Button ID="btnBuscar" runat="server" Text="Buscar" 
                                CssClass="btn rounded btn_search" ValidationGroup="valPol" 
                                onclick="btnBuscar_Click"/>
                                 
                                <asp:Label ID="lbResultados" runat="server" CssClass="infoResultado rounded" 
                                Visible="False" ></asp:Label>
                             </td>
                        
                    </tr>

                </tbody>
            </table>
            
            
        </div>
        
        <div>
           
            <asp:Button ID="btnNuevo" runat="server" Text="Nuevo Objeto" 
                CssClass="btn rounded btn_add fright" style="margin-right:0px;" onclick="btnNuevo_Click" 
               /> 
            <div class="clear"></div>
             <h2>Listado de Menus</h2>
 
             <div class="sub-panel">
                                
                <asp:Button ID="btnEditar" runat="server" Text="Editar" 
                     CssClass="btn rounded  btn_unlock" onclick="btnEditar_Click" style = "margin-left:8px;" 
                     Width="100px" />
               
                <asp:Button ID="btnEliminar" runat="server" Text="Eliminar" 
                     CssClass="btn rounded btn_cancel" onclick="btnEliminar_Click" Width="100px" />
                
                                  <br/>
                 <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                 <ContentTemplate>

                 
                 
                 <asp:TreeView ID="tvObjetos" runat="server" ImageSet="XPFileExplorer" 
                    NodeIndent="45" ShowLines="True" AutoGenerateDataBindings="False" 
                     PopulateNodesFromClient="true"
                     ExpandDepth="0" 
                      ShowExpandCollapse="true"
                    CssClass="tvSize rounded">
                    <ParentNodeStyle Font-Bold="False" />
                    <HoverNodeStyle Font-Underline="True" ForeColor="#6666AA" />
                    <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" 
                        HorizontalPadding="0px" VerticalPadding="0px" />
                    <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="Black" 
                        HorizontalPadding="2px" NodeSpacing="0px" VerticalPadding="2px" />
                </asp:TreeView>
                                 </ContentTemplate>
                 </asp:UpdatePanel>
                
            </div>
        </div>
    </div>
</asp:Content>
